import type { Patient, ActivityItem, ChartDataPoint, DepartmentData, DemographicsData, RevenueData, Notification } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'James Anderson',
    age: 54,
    gender: 'Male',
    condition: 'Hypertension',
    status: 'Active',
    department: 'Cardiology',
    doctor: 'Dr. Sarah Mitchell',
    admissionDate: '2024-01-15',
    lastVisit: '2024-03-10',
    phone: '+1 (555) 234-5678',
    email: 'james.anderson@email.com',
    address: '123 Oak Street, Boston, MA 02101',
    bloodGroup: 'O+',
    insurance: 'BlueCross BlueShield',
    notes: 'Patient requires regular monitoring of blood pressure. Medication adjusted last visit.',
    vitals: { bloodPressure: '145/95', heartRate: 78, temperature: 98.6, oxygenSaturation: 97, weight: 185, height: 72 },
    medications: ['Lisinopril 10mg', 'Amlodipine 5mg', 'Aspirin 81mg'],
    allergies: ['Penicillin'],
  },
  {
    id: 'P002',
    name: 'Maria Santos',
    age: 32,
    gender: 'Female',
    condition: 'Appendicitis (Post-op)',
    status: 'Recovered',
    department: 'General Medicine',
    doctor: 'Dr. Kevin Park',
    admissionDate: '2024-02-20',
    lastVisit: '2024-03-05',
    phone: '+1 (555) 345-6789',
    email: 'maria.santos@email.com',
    address: '456 Maple Ave, Chicago, IL 60601',
    bloodGroup: 'A+',
    insurance: 'Aetna',
    notes: 'Post-operative recovery progressing well. Follow-up in 2 weeks.',
    vitals: { bloodPressure: '118/76', heartRate: 72, temperature: 98.4, oxygenSaturation: 99, weight: 135, height: 65 },
    medications: ['Amoxicillin 500mg', 'Ibuprofen 400mg'],
    allergies: [],
  },
  {
    id: 'P003',
    name: 'Robert Chen',
    age: 67,
    gender: 'Male',
    condition: 'Acute MI',
    status: 'Critical',
    department: 'Cardiology',
    doctor: 'Dr. Sarah Mitchell',
    admissionDate: '2024-03-08',
    lastVisit: '2024-03-10',
    phone: '+1 (555) 456-7890',
    email: 'robert.chen@email.com',
    address: '789 Pine Rd, New York, NY 10001',
    bloodGroup: 'B-',
    insurance: 'Medicare',
    notes: 'Admitted with acute MI. Currently in CCU. Stable but critical.',
    vitals: { bloodPressure: '90/60', heartRate: 105, temperature: 99.2, oxygenSaturation: 92, weight: 175, height: 70 },
    medications: ['Heparin IV', 'Aspirin 325mg', 'Metoprolol 25mg', 'Atorvastatin 80mg'],
    allergies: ['Sulfa drugs'],
  },
  {
    id: 'P004',
    name: 'Emily Johnson',
    age: 28,
    gender: 'Female',
    condition: 'Anxiety Disorder',
    status: 'Pending',
    department: 'Psychiatry',
    doctor: 'Dr. Lisa Patel',
    admissionDate: '2024-03-01',
    lastVisit: '2024-03-07',
    phone: '+1 (555) 567-8901',
    email: 'emily.johnson@email.com',
    address: '321 Elm Street, Seattle, WA 98101',
    bloodGroup: 'AB+',
    insurance: 'UnitedHealth',
    notes: 'New patient. Assessment pending. Initial consultation completed.',
    vitals: { bloodPressure: '120/80', heartRate: 88, temperature: 98.6, oxygenSaturation: 98, weight: 130, height: 64 },
    medications: ['Sertraline 50mg'],
    allergies: ['Latex'],
  },
  {
    id: 'P005',
    name: 'David Williams',
    age: 45,
    gender: 'Male',
    condition: 'Type 2 Diabetes',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2023-11-10',
    lastVisit: '2024-03-08',
    phone: '+1 (555) 678-9012',
    email: 'david.williams@email.com',
    address: '654 Birch Lane, Houston, TX 77001',
    bloodGroup: 'O-',
    insurance: 'Cigna',
    notes: 'HbA1c levels improving with new medication regimen. Diet counseling ongoing.',
    vitals: { bloodPressure: '135/85', heartRate: 74, temperature: 98.5, oxygenSaturation: 98, weight: 210, height: 71 },
    medications: ['Metformin 1000mg', 'Glipizide 5mg', 'Lisinopril 5mg'],
    allergies: ['Codeine'],
  },
  {
    id: 'P006',
    name: 'Linda Garcia',
    age: 58,
    gender: 'Female',
    condition: 'Breast Cancer (Stage II)',
    status: 'Active',
    department: 'Oncology',
    doctor: 'Dr. Rachel Kim',
    admissionDate: '2024-01-05',
    lastVisit: '2024-03-09',
    phone: '+1 (555) 789-0123',
    email: 'linda.garcia@email.com',
    address: '987 Cedar Ave, Phoenix, AZ 85001',
    bloodGroup: 'A-',
    insurance: 'Humana',
    notes: 'Currently in 3rd cycle of chemotherapy. Responding well to treatment.',
    vitals: { bloodPressure: '122/78', heartRate: 80, temperature: 98.8, oxygenSaturation: 97, weight: 145, height: 63 },
    medications: ['Tamoxifen 20mg', 'Ondansetron 8mg', 'Dexamethasone 4mg'],
    allergies: ['NSAIDs'],
  },
  {
    id: 'P007',
    name: 'Michael Brown',
    age: 39,
    gender: 'Male',
    condition: 'Herniated Disc',
    status: 'Pending',
    department: 'Orthopedics',
    doctor: 'Dr. James Wilson',
    admissionDate: '2024-02-28',
    lastVisit: '2024-03-06',
    phone: '+1 (555) 890-1234',
    email: 'michael.brown@email.com',
    address: '147 Willow Way, Denver, CO 80201',
    bloodGroup: 'B+',
    insurance: 'BlueCross BlueShield',
    notes: 'Awaiting MRI results. Conservative treatment ongoing.',
    vitals: { bloodPressure: '126/82', heartRate: 76, temperature: 98.6, oxygenSaturation: 99, weight: 190, height: 73 },
    medications: ['Cyclobenzaprine 10mg', 'Naproxen 500mg'],
    allergies: [],
  },
  {
    id: 'P008',
    name: 'Susan Taylor',
    age: 72,
    gender: 'Female',
    condition: 'Stroke (Ischemic)',
    status: 'Critical',
    department: 'Neurology',
    doctor: 'Dr. Amanda Foster',
    admissionDate: '2024-03-09',
    lastVisit: '2024-03-10',
    phone: '+1 (555) 901-2345',
    email: 'susan.taylor@email.com',
    address: '258 Oakwood Dr, Philadelphia, PA 19101',
    bloodGroup: 'AB-',
    insurance: 'Medicare',
    notes: 'Admitted with ischemic stroke. tPA administered within window. Monitoring closely.',
    vitals: { bloodPressure: '165/100', heartRate: 92, temperature: 99.0, oxygenSaturation: 94, weight: 155, height: 62 },
    medications: ['Alteplase IV', 'Aspirin 325mg', 'Atorvastatin 40mg', 'Labetalol IV'],
    allergies: ['Morphine'],
  },
  {
    id: 'P009',
    name: 'Christopher Davis',
    age: 16,
    gender: 'Male',
    condition: 'Asthma',
    status: 'Active',
    department: 'Pediatrics',
    doctor: 'Dr. Nancy Rodriguez',
    admissionDate: '2024-02-15',
    lastVisit: '2024-03-04',
    phone: '+1 (555) 012-3456',
    email: 'c.davis.parent@email.com',
    address: '369 Spruce St, Minneapolis, MN 55401',
    bloodGroup: 'O+',
    insurance: 'Medicaid',
    notes: 'Moderate persistent asthma. Good compliance with inhaler therapy.',
    vitals: { bloodPressure: '110/70', heartRate: 82, temperature: 98.4, oxygenSaturation: 96, weight: 145, height: 68 },
    medications: ['Albuterol MDI', 'Fluticasone 110mcg', 'Montelukast 10mg'],
    allergies: ['Dust mites', 'Pollen'],
  },
  {
    id: 'P010',
    name: 'Patricia Martinez',
    age: 49,
    gender: 'Female',
    condition: 'Rheumatoid Arthritis',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2023-09-20',
    lastVisit: '2024-03-01',
    phone: '+1 (555) 123-4567',
    email: 'patricia.martinez@email.com',
    address: '741 Redwood Blvd, Portland, OR 97201',
    bloodGroup: 'A+',
    insurance: 'Aetna',
    notes: 'RA management ongoing. Biologic therapy initiated last month.',
    vitals: { bloodPressure: '128/84', heartRate: 78, temperature: 98.7, oxygenSaturation: 98, weight: 148, height: 63 },
    medications: ['Methotrexate 15mg weekly', 'Adalimumab 40mg biweekly', 'Folic acid 1mg'],
    allergies: ['Aspirin'],
  },
  {
    id: 'P011',
    name: 'Thomas Wilson',
    age: 61,
    gender: 'Male',
    condition: 'COPD',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Kevin Park',
    admissionDate: '2023-10-05',
    lastVisit: '2024-02-28',
    phone: '+1 (555) 234-5670',
    email: 'thomas.wilson@email.com',
    address: '852 Aspen Ct, Las Vegas, NV 89101',
    bloodGroup: 'B+',
    insurance: 'UnitedHealth',
    notes: 'COPD GOLD Stage III. Pulmonary rehab in progress.',
    vitals: { bloodPressure: '138/88', heartRate: 86, temperature: 98.6, oxygenSaturation: 89, weight: 168, height: 69 },
    medications: ['Tiotropium 18mcg', 'Salmeterol/Fluticasone', 'Prednisone 10mg PRN'],
    allergies: [],
  },
  {
    id: 'P012',
    name: 'Jennifer Lee',
    age: 35,
    gender: 'Female',
    condition: 'Ectopic Pregnancy',
    status: 'Recovered',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2024-02-10',
    lastVisit: '2024-03-02',
    phone: '+1 (555) 345-6780',
    email: 'jennifer.lee@email.com',
    address: '963 Poplar Rd, San Antonio, TX 78201',
    bloodGroup: 'O-',
    insurance: 'Cigna',
    notes: 'Surgical intervention successful. Full recovery expected.',
    vitals: { bloodPressure: '116/74', heartRate: 70, temperature: 98.5, oxygenSaturation: 99, weight: 128, height: 64 },
    medications: ['Iron supplements', 'Folic acid 5mg'],
    allergies: ['Iodine contrast'],
  },
  {
    id: 'P013',
    name: 'Charles Thompson',
    age: 78,
    gender: 'Male',
    condition: 'Atrial Fibrillation',
    status: 'Active',
    department: 'Cardiology',
    doctor: 'Dr. Sarah Mitchell',
    admissionDate: '2023-12-01',
    lastVisit: '2024-03-07',
    phone: '+1 (555) 456-7891',
    email: 'charles.thompson@email.com',
    address: '174 Magnolia Lane, Baltimore, MD 21201',
    bloodGroup: 'A-',
    insurance: 'Medicare',
    notes: 'AFib with rate control. Anticoagulation therapy ongoing.',
    vitals: { bloodPressure: '132/82', heartRate: 94, temperature: 98.4, oxygenSaturation: 96, weight: 172, height: 68 },
    medications: ['Apixaban 5mg', 'Digoxin 0.125mg', 'Carvedilol 6.25mg'],
    allergies: ['Warfarin intolerance'],
  },
  {
    id: 'P014',
    name: 'Jessica Harris',
    age: 27,
    gender: 'Female',
    condition: 'Migraine',
    status: 'Pending',
    department: 'Neurology',
    doctor: 'Dr. Amanda Foster',
    admissionDate: '2024-03-05',
    lastVisit: '2024-03-05',
    phone: '+1 (555) 567-8902',
    email: 'jessica.harris@email.com',
    address: '285 Walnut St, Memphis, TN 38101',
    bloodGroup: 'B-',
    insurance: 'Humana',
    notes: 'Frequent migraines with aura. Preventive therapy under evaluation.',
    vitals: { bloodPressure: '118/76', heartRate: 74, temperature: 98.6, oxygenSaturation: 99, weight: 125, height: 66 },
    medications: ['Sumatriptan 50mg PRN', 'Topiramate 25mg'],
    allergies: ['Ergotamine'],
  },
  {
    id: 'P015',
    name: 'Daniel Jackson',
    age: 52,
    gender: 'Male',
    condition: 'Colorectal Cancer',
    status: 'Active',
    department: 'Oncology',
    doctor: 'Dr. Rachel Kim',
    admissionDate: '2024-01-20',
    lastVisit: '2024-03-08',
    phone: '+1 (555) 678-9013',
    email: 'daniel.jackson@email.com',
    address: '396 Hickory Ave, Louisville, KY 40201',
    bloodGroup: 'AB+',
    insurance: 'BlueCross BlueShield',
    notes: 'Stage III CRC. Post-surgical chemotherapy ongoing.',
    vitals: { bloodPressure: '125/80', heartRate: 78, temperature: 98.7, oxygenSaturation: 97, weight: 178, height: 71 },
    medications: ['FOLFOX regimen', 'Ondansetron 8mg', 'Leucovorin'],
    allergies: [],
  },
  {
    id: 'P016',
    name: 'Nancy White',
    age: 43,
    gender: 'Female',
    condition: 'Psoriasis',
    status: 'Active',
    department: 'Dermatology',
    doctor: 'Dr. Paul Young',
    admissionDate: '2023-08-15',
    lastVisit: '2024-02-25',
    phone: '+1 (555) 789-0124',
    email: 'nancy.white@email.com',
    address: '507 Chestnut Blvd, Milwaukee, WI 53201',
    bloodGroup: 'O+',
    insurance: 'Aetna',
    notes: 'Moderate-to-severe plaque psoriasis. Biologic therapy starting.',
    vitals: { bloodPressure: '122/78', heartRate: 72, temperature: 98.5, oxygenSaturation: 98, weight: 152, height: 65 },
    medications: ['Adalimumab 40mg biweekly', 'Triamcinolone cream'],
    allergies: ['Neomycin'],
  },
  {
    id: 'P017',
    name: 'George Lewis',
    age: 70,
    gender: 'Male',
    condition: 'Parkinson\'s Disease',
    status: 'Active',
    department: 'Neurology',
    doctor: 'Dr. Amanda Foster',
    admissionDate: '2023-06-01',
    lastVisit: '2024-03-06',
    phone: '+1 (555) 890-1235',
    email: 'george.lewis@email.com',
    address: '618 Sycamore Dr, Albuquerque, NM 87101',
    bloodGroup: 'A+',
    insurance: 'Medicare',
    notes: 'Stage 2 Parkinson\'s. DBS evaluation scheduled.',
    vitals: { bloodPressure: '128/82', heartRate: 76, temperature: 98.4, oxygenSaturation: 97, weight: 165, height: 70 },
    medications: ['Levodopa/Carbidopa 25-100mg', 'Pramipexole 0.5mg', 'Rasagiline 1mg'],
    allergies: [],
  },
  {
    id: 'P018',
    name: 'Angela Robinson',
    age: 38,
    gender: 'Female',
    condition: 'Crohn\'s Disease',
    status: 'Active',
    department: 'Gastroenterology',
    doctor: 'Dr. Brian Hall',
    admissionDate: '2023-11-25',
    lastVisit: '2024-03-03',
    phone: '+1 (555) 901-2346',
    email: 'angela.robinson@email.com',
    address: '729 Cottonwood Ct, Tucson, AZ 85701',
    bloodGroup: 'B+',
    insurance: 'UnitedHealth',
    notes: 'Moderate Crohn\'s with ileocolonic involvement. Biologic induction completed.',
    vitals: { bloodPressure: '115/73', heartRate: 80, temperature: 98.8, oxygenSaturation: 98, weight: 118, height: 62 },
    medications: ['Infliximab 5mg/kg IV', 'Azathioprine 150mg', 'Mesalamine 4g'],
    allergies: ['Metronidazole'],
  },
  {
    id: 'P019',
    name: 'Kevin Walker',
    age: 55,
    gender: 'Male',
    condition: 'Kidney Stones',
    status: 'Recovered',
    department: 'General Medicine',
    doctor: 'Dr. Kevin Park',
    admissionDate: '2024-02-25',
    lastVisit: '2024-03-08',
    phone: '+1 (555) 012-3457',
    email: 'kevin.walker@email.com',
    address: '840 Alder Lane, Fresno, CA 93701',
    bloodGroup: 'O+',
    insurance: 'Cigna',
    notes: 'Ureterolithiasis treated with lithotripsy. Follow-up urinalysis clear.',
    vitals: { bloodPressure: '124/80', heartRate: 74, temperature: 98.6, oxygenSaturation: 99, weight: 182, height: 72 },
    medications: ['Tamsulosin 0.4mg', 'Potassium citrate 15mEq'],
    allergies: [],
  },
  {
    id: 'P020',
    name: 'Helen Young',
    age: 65,
    gender: 'Female',
    condition: 'Osteoporosis',
    status: 'Active',
    department: 'Orthopedics',
    doctor: 'Dr. James Wilson',
    admissionDate: '2023-07-10',
    lastVisit: '2024-02-20',
    phone: '+1 (555) 123-4568',
    email: 'helen.young@email.com',
    address: '951 Beech St, Sacramento, CA 95801',
    bloodGroup: 'A-',
    insurance: 'Humana',
    notes: 'Dual-energy X-ray absorptiometry shows T-score -2.8. Anti-resorptive therapy ongoing.',
    vitals: { bloodPressure: '130/84', heartRate: 72, temperature: 98.5, oxygenSaturation: 97, weight: 135, height: 61 },
    medications: ['Alendronate 70mg weekly', 'Calcium 600mg BD', 'Vitamin D3 1000IU'],
    allergies: ['NSAIDs'],
  },
  {
    id: 'P021',
    name: 'Steven King',
    age: 41,
    gender: 'Male',
    condition: 'Sleep Apnea',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2024-01-08',
    lastVisit: '2024-03-05',
    phone: '+1 (555) 234-5671',
    email: 'steven.king@email.com',
    address: '162 Fir Ave, Kansas City, MO 64101',
    bloodGroup: 'B-',
    insurance: 'Aetna',
    notes: 'Severe OSA. CPAP initiated. Titration scheduled.',
    vitals: { bloodPressure: '140/90', heartRate: 82, temperature: 98.6, oxygenSaturation: 95, weight: 245, height: 70 },
    medications: ['CPAP therapy', 'Modafinil 200mg'],
    allergies: [],
  },
  {
    id: 'P022',
    name: 'Karen Scott',
    age: 47,
    gender: 'Female',
    condition: 'Hypothyroidism',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2023-05-12',
    lastVisit: '2024-03-01',
    phone: '+1 (555) 345-6781',
    email: 'karen.scott@email.com',
    address: '273 Cypress Rd, Omaha, NE 68101',
    bloodGroup: 'O+',
    insurance: 'BlueCross BlueShield',
    notes: 'Hashimoto\'s thyroiditis. Levothyroxine dose recently adjusted.',
    vitals: { bloodPressure: '120/76', heartRate: 68, temperature: 97.8, oxygenSaturation: 98, weight: 158, height: 65 },
    medications: ['Levothyroxine 75mcg'],
    allergies: [],
  },
  {
    id: 'P023',
    name: 'Donald Hill',
    age: 59,
    gender: 'Male',
    condition: 'Peripheral Artery Disease',
    status: 'Pending',
    department: 'Cardiology',
    doctor: 'Dr. Sarah Mitchell',
    admissionDate: '2024-03-07',
    lastVisit: '2024-03-07',
    phone: '+1 (555) 456-7892',
    email: 'donald.hill@email.com',
    address: '384 Laurel Dr, Tulsa, OK 74101',
    bloodGroup: 'AB+',
    insurance: 'Medicare',
    notes: 'ABI test ordered. Vascular surgery consult pending.',
    vitals: { bloodPressure: '150/95', heartRate: 84, temperature: 98.6, oxygenSaturation: 96, weight: 195, height: 71 },
    medications: ['Clopidogrel 75mg', 'Cilostazol 100mg', 'Atorvastatin 40mg'],
    allergies: ['Aspirin'],
  },
  {
    id: 'P024',
    name: 'Lisa Turner',
    age: 30,
    gender: 'Female',
    condition: 'Lupus (SLE)',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2023-10-15',
    lastVisit: '2024-03-04',
    phone: '+1 (555) 567-8903',
    email: 'lisa.turner@email.com',
    address: '495 Jasmine Court, Raleigh, NC 27601',
    bloodGroup: 'B+',
    insurance: 'Cigna',
    notes: 'SLE with nephritis. Immunosuppression therapy ongoing.',
    vitals: { bloodPressure: '125/80', heartRate: 76, temperature: 99.1, oxygenSaturation: 98, weight: 130, height: 64 },
    medications: ['Hydroxychloroquine 400mg', 'Mycophenolate 1500mg BD', 'Prednisone 10mg'],
    allergies: ['Sulfonamides'],
  },
  {
    id: 'P025',
    name: 'Paul Adams',
    age: 63,
    gender: 'Male',
    condition: 'Glaucoma',
    status: 'Active',
    department: 'General Medicine',
    doctor: 'Dr. Kevin Park',
    admissionDate: '2023-04-20',
    lastVisit: '2024-02-15',
    phone: '+1 (555) 678-9014',
    email: 'paul.adams@email.com',
    address: '606 Iris Way, Richmond, VA 23201',
    bloodGroup: 'A+',
    insurance: 'UnitedHealth',
    notes: 'Open-angle glaucoma bilateral. IOP controlled with drops.',
    vitals: { bloodPressure: '134/86', heartRate: 74, temperature: 98.5, oxygenSaturation: 97, weight: 178, height: 70 },
    medications: ['Latanoprost 0.005% eye drops', 'Timolol 0.5% eye drops'],
    allergies: [],
  },
  {
    id: 'P026',
    name: 'Sandra Nelson',
    age: 36,
    gender: 'Female',
    condition: 'Preeclampsia',
    status: 'Critical',
    department: 'General Medicine',
    doctor: 'Dr. Mark Thompson',
    admissionDate: '2024-03-09',
    lastVisit: '2024-03-10',
    phone: '+1 (555) 789-0125',
    email: 'sandra.nelson@email.com',
    address: '717 Orchid Blvd, Baton Rouge, LA 70801',
    bloodGroup: 'A+',
    insurance: 'Medicaid',
    notes: 'Admitted with severe preeclampsia at 36 weeks. Magnesium sulfate infusion.',
    vitals: { bloodPressure: '170/110', heartRate: 96, temperature: 99.4, oxygenSaturation: 96, weight: 182, height: 64 },
    medications: ['Magnesium sulfate IV', 'Labetalol 200mg', 'Betamethasone IM'],
    allergies: [],
  },
  {
    id: 'P027',
    name: 'Edward Baker',
    age: 48,
    gender: 'Male',
    condition: 'Pancreatitis',
    status: 'Recovered',
    department: 'Gastroenterology',
    doctor: 'Dr. Brian Hall',
    admissionDate: '2024-02-18',
    lastVisit: '2024-03-06',
    phone: '+1 (555) 890-1236',
    email: 'edward.baker@email.com',
    address: '828 Tulip Lane, Jacksonville, FL 32201',
    bloodGroup: 'O-',
    insurance: 'Humana',
    notes: 'Acute pancreatitis resolved. Dietary counseling completed.',
    vitals: { bloodPressure: '122/78', heartRate: 72, temperature: 98.4, oxygenSaturation: 99, weight: 185, height: 71 },
    medications: ['Enzyme replacement therapy', 'Omeprazole 20mg'],
    allergies: ['Morphine'],
  },
  {
    id: 'P028',
    name: 'Donna Campbell',
    age: 55,
    gender: 'Female',
    condition: 'Multiple Sclerosis',
    status: 'Active',
    department: 'Neurology',
    doctor: 'Dr. Amanda Foster',
    admissionDate: '2023-09-01',
    lastVisit: '2024-03-02',
    phone: '+1 (555) 901-2347',
    email: 'donna.campbell@email.com',
    address: '939 Peony Dr, Columbus, OH 43201',
    bloodGroup: 'B-',
    insurance: 'Aetna',
    notes: 'RRMS. Natalizumab infusions ongoing. JC antibody negative.',
    vitals: { bloodPressure: '118/74', heartRate: 70, temperature: 98.6, oxygenSaturation: 98, weight: 138, height: 64 },
    medications: ['Natalizumab 300mg IV monthly', 'Baclofen 10mg TID', 'Modafinil 200mg'],
    allergies: [],
  },
  {
    id: 'P029',
    name: 'Richard Mitchell',
    age: 44,
    gender: 'Male',
    condition: 'Gout',
    status: 'Recovered',
    department: 'Orthopedics',
    doctor: 'Dr. James Wilson',
    admissionDate: '2024-02-22',
    lastVisit: '2024-03-04',
    phone: '+1 (555) 012-3458',
    email: 'richard.mitchell@email.com',
    address: '1050 Dahlia St, Indianapolis, IN 46201',
    bloodGroup: 'A-',
    insurance: 'BlueCross BlueShield',
    notes: 'Acute gout flare resolved. Uric acid-lowering therapy initiated.',
    vitals: { bloodPressure: '128/82', heartRate: 76, temperature: 98.5, oxygenSaturation: 99, weight: 195, height: 72 },
    medications: ['Allopurinol 300mg', 'Colchicine 0.6mg BD'],
    allergies: ['NSAIDs'],
  },
  {
    id: 'P030',
    name: 'Betty Price',
    age: 82,
    gender: 'Female',
    condition: 'Heart Failure',
    status: 'Critical',
    department: 'Cardiology',
    doctor: 'Dr. Sarah Mitchell',
    admissionDate: '2024-03-08',
    lastVisit: '2024-03-10',
    phone: '+1 (555) 123-4569',
    email: 'betty.price@email.com',
    address: '1161 Violet Way, Charlotte, NC 28201',
    bloodGroup: 'O+',
    insurance: 'Medicare',
    notes: 'NYHA Class IV HFrEF. Decompensated. IV diuresis initiated.',
    vitals: { bloodPressure: '88/60', heartRate: 110, temperature: 98.8, oxygenSaturation: 90, weight: 162, height: 60 },
    medications: ['Furosemide 80mg IV', 'Carvedilol 25mg', 'Sacubitril/Valsartan 97/103mg', 'Spironolactone 25mg'],
    allergies: ['ACE inhibitors'],
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: 'A001',
    type: 'admission',
    message: 'New patient Robert Chen admitted to Cardiology',
    time: '10 minutes ago',
    patient: 'Robert Chen',
    severity: 'warning',
  },
  {
    id: 'A002',
    type: 'alert',
    message: 'Critical vitals alert for Betty Price — O2 sat 90%',
    time: '25 minutes ago',
    patient: 'Betty Price',
    severity: 'error',
  },
  {
    id: 'A003',
    type: 'discharge',
    message: 'Patient Kevin Walker successfully discharged',
    time: '1 hour ago',
    patient: 'Kevin Walker',
    severity: 'success',
  },
  {
    id: 'A004',
    type: 'appointment',
    message: 'Appointment scheduled for Emily Johnson — Psychiatry',
    time: '2 hours ago',
    patient: 'Emily Johnson',
    severity: 'info',
  },
  {
    id: 'A005',
    type: 'report',
    message: 'Lab results ready for Linda Garcia — Oncology',
    time: '3 hours ago',
    patient: 'Linda Garcia',
    severity: 'info',
  },
  {
    id: 'A006',
    type: 'alert',
    message: 'Susan Taylor BP rising — Neurology ICU',
    time: '4 hours ago',
    patient: 'Susan Taylor',
    severity: 'error',
  },
  {
    id: 'A007',
    type: 'admission',
    message: 'Sandra Nelson admitted — Obstetrics (Emergency)',
    time: '5 hours ago',
    patient: 'Sandra Nelson',
    severity: 'warning',
  },
];

export const admissionsData: ChartDataPoint[] = [
  { month: 'Oct', value: 42 },
  { month: 'Nov', value: 58 },
  { month: 'Dec', value: 47 },
  { month: 'Jan', value: 65 },
  { month: 'Feb', value: 72 },
  { month: 'Mar', value: 89 },
];

export const departmentData: DepartmentData[] = [
  { name: 'Cardiology', patients: 8, fill: '#6366f1' },
  { name: 'Neurology', patients: 5, fill: '#8b5cf6' },
  { name: 'Orthopedics', patients: 4, fill: '#06b6d4' },
  { name: 'Oncology', patients: 3, fill: '#f59e0b' },
  { name: 'Pediatrics', patients: 2, fill: '#10b981' },
  { name: 'Emergency', patients: 3, fill: '#ef4444' },
  { name: 'General Medicine', patients: 9, fill: '#3b82f6' },
  { name: 'Dermatology', patients: 2, fill: '#ec4899' },
  { name: 'Psychiatry', patients: 2, fill: '#f97316' },
  { name: 'Gastroenterology', patients: 2, fill: '#84cc16' },
];

export const demographicsData: DemographicsData[] = [
  { name: '0-17', value: 3, fill: '#6366f1' },
  { name: '18-35', value: 7, fill: '#8b5cf6' },
  { name: '36-50', value: 9, fill: '#06b6d4' },
  { name: '51-65', value: 7, fill: '#f59e0b' },
  { name: '65+', value: 6, fill: '#10b981' },
];

export const revenueData: RevenueData[] = [
  { month: 'Oct', revenue: 420000, expenses: 280000 },
  { month: 'Nov', revenue: 485000, expenses: 310000 },
  { month: 'Dec', revenue: 390000, expenses: 265000 },
  { month: 'Jan', revenue: 520000, expenses: 320000 },
  { month: 'Feb', revenue: 580000, expenses: 345000 },
  { month: 'Mar', revenue: 635000, expenses: 380000 },
];

export const mockNotifications: Notification[] = [
  {
    id: 'N001',
    title: 'Critical Alert',
    message: 'Patient Betty Price — O2 saturation critical (90%)',
    time: '25 min ago',
    read: false,
    type: 'error',
  },
  {
    id: 'N002',
    title: 'New Admission',
    message: 'Robert Chen admitted to Cardiology CCU',
    time: '10 min ago',
    read: false,
    type: 'warning',
  },
  {
    id: 'N003',
    title: 'Lab Results Ready',
    message: 'Linda Garcia — Complete blood count results available',
    time: '1 hr ago',
    read: false,
    type: 'info',
  },
  {
    id: 'N004',
    title: 'Patient Discharged',
    message: 'Kevin Walker successfully discharged',
    time: '2 hr ago',
    read: true,
    type: 'success',
  },
  {
    id: 'N005',
    title: 'Appointment Reminder',
    message: 'Emily Johnson — Psychiatry follow-up tomorrow at 10:00 AM',
    time: '3 hr ago',
    read: true,
    type: 'info',
  },
];
